JiuFu/JiuFu.Web/Controllers/FoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JiuFu.Entities;
using JiuFu.ORM.SqlServer;
using JiuFu.Web.Models;
using Microsoft.AspNetCore.Authorization;

namespace JiuFu.Web.Controllers
{
    public class FoodsController : Controller
    {
        private readonly SqlServerDbContext _context;
        public FoodsController(SqlServerDbContext context)
        {
            _context = context;
        }

        // GET: Foods
        public async Task<IActionResult> Index(string searchString)
        {
             var s = await _context.Foods.OrderBy(x => x.FoodClass.Name).ToArrayAsync();
            List<FoodViewModel> fm = new List<FoodViewModel>();
            foreach (var f in s)
            {
                Guid guid = f.FoodClassId;
                var st = _context.FoodClass.Single(x => x.Id == guid);
                var tt = new FoodViewModel { Id=f.Id, Name = f.Name, Detail = f.Detail, picture = f.picture, Price = f.Price, ClassName = st.Name };
                fm.Add(tt);
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                s = await _context.Foods.Where(x=>x.Name==searchString).OrderBy(x => x.FoodClass.Name).ToArrayAsync();
                fm = new List<FoodViewModel>();
                foreach (var f in s)
                {
                    Guid guid = f.FoodClassId;
                    var st = _context.FoodClass.Single(x => x.Id == guid);
                    var tt = new FoodViewModel { Id = f.Id, Name = f.Name, Detail = f.Detail, picture = f.picture, Price = f.Price, ClassName = st.Name };
                    fm.Add(tt);
                }               
            }
            return View(fm);
        }

        // GET: Foods/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var food = await _context.Foods
                .FirstOrDefaultAsync(m => m.Id == id);
            Guid Id = food.flavorId;
            var dge =  _context.Degrees.Where(x=>x.Flavors.Id==food.flavorId).ToList();        
          
            FoodOrderViewModel fo = new FoodOrderViewModel { foodid = food.Id, picture = food.picture,Price=food.Price,Name=food.Name,Number="1",Remarks="",FoodState=new FoodStateEnum(),degree=dge};
            return View(fo);
        }

        // GET: Foods/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Foods/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,Detail,SaleState,picture")] Food food)
        {
            if (ModelState.IsValid)
            {
                food.Id = Guid.NewGuid();
                _context.Add(food);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(food);
        }

        // GET: Foods/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Foods.FindAsync(id);
            if (food == null)
            {
                return NotFound();
            }
            return View(food);
        }

        // POST: Foods/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Price,Detail,SaleState,picture")] Food food)
        {
            if (id != food.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(food);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FoodExists(food.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(food);
        }

        // GET: Foods/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Foods
                .FirstOrDefaultAsync(m => m.Id == id);
            if (food == null)
            {
                return NotFound();
            }

            return View(food);
        }

        // POST: Foods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var food = await _context.Foods.FindAsync(id);
            _context.Foods.Remove(food);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FoodExists(Guid id)
        {
            return _context.Foods.Any(e => e.Id == id);
        }

        public IActionResult FoodOrderCreate()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FoodOrderCreate( FoodOrderViewModel foodorder)
        {
            var food = _context.Foods.Single(x=>x.Id== foodorder.foodid);
            var foodorders = new FoodOrder { Food= food,Number=foodorder.Number,Remarks=foodorder.Remarks,FoodState=foodorder.FoodState,FlarNames=foodorder.degrees,OrderStatus=true };
            _context.FoodOrders.Add(foodorders);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

JiuFu/JiuFu.Web/Controllers/GoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JiuFu.Entities;
using JiuFu.ORM.SqlServer;
using JiuFu.Web.Models;

namespace JiuFu.Web.Controllers
{
    public class GoodsController : Controller
    {
        private readonly SqlServerDbContext _context;

        public GoodsController(SqlServerDbContext context)
        {
            _context = context;
        }

        // GET: Goods
        public async Task<IActionResult> Index()
        {
            return View(await _context.Goodss.ToListAsync());
        }

        // GET: Goods/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var goods = await _context.Goodss
                .FirstOrDefaultAsync(m => m.Id == id);
            GoodsOrderViewModel fo = new GoodsOrderViewModel { goodid = goods.Id, picture = goods.picture, Price = goods.Price, Name = goods.Name, Number = "1", Remarks = "" };
            return View(fo);
        }

        // GET: Goods/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Goods/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,Detail,picture")] Goods goods)
        {
            if (ModelState.IsValid)
            {
                goods.Id = Guid.NewGuid();
                _context.Add(goods);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(goods);
        }

        // GET: Goods/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var goods = await _context.Goodss.FindAsync(id);
            if (goods == null)
            {
                return NotFound();
            }
            return View(goods);
        }

        // POST: Goods/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Price,Detail,picture")] Goods goods)
        {
            if (id != goods.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(goods);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GoodsExists(goods.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(goods);
        }

        // GET: Goods/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var goods = await _context.Goodss
                .FirstOrDefaultAsync(m => m.Id == id);
            if (goods == null)
            {
                return NotFound();
            }

            return View(goods);
        }

        // POST: Goods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var goods = await _context.Goodss.FindAsync(id);
            _context.Goodss.Remove(goods);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GoodsExists(Guid id)
        {
            return _context.Goodss.Any(e => e.Id == id);
        }

        public IActionResult GoodsOrderCreate()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GoodsOrderCreate( GoodsOrderViewModel goodsorder)
        {
            var good = _context.Goodss.Single(x => x.Id == goodsorder.goodid);
            var goodorders = new GoodsOrder { Goods = good, Name = goodsorder.Name, Number = goodsorder.Number, Remarks = goodsorder.Remarks, State = goodsorder.GoodState, GoodsId=good.Id, OrderStatus = true };
            _context.GoodsOrders.Add(goodorders);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

JiuFu/JiuFu.Web/Controllers/ScenicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JiuFu.Entities;
using JiuFu.ORM.SqlServer;

namespace JiuFu.Web.Controllers
{
    public class ScenicsController : Controller
    {
        private readonly SqlServerDbContext _context;

        public ScenicsController(SqlServerDbContext context)
        {
            _context = context;
        }

        // GET: Scenics
        public async Task<IActionResult> Index()
        {
            return View(await _context.Scenics.ToListAsync());
        }

        // GET: Scenics/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scenic = await _context.Scenics
                .FirstOrDefaultAsync(m => m.Id == id);
            if (scenic == null)
            {
                return NotFound();
            }

            return View(scenic);
        }

        // GET: Scenics/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Scenics/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Position,Date,Detail,picture")] Scenic scenic)
        {
            if (ModelState.IsValid)
            {
                scenic.Id = Guid.NewGuid();
                _context.Add(scenic);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(scenic);
        }

        // GET: Scenics/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scenic = await _context.Scenics.FindAsync(id);
            if (scenic == null)
            {
                return NotFound();
            }
            return View(scenic);
        }

        // POST: Scenics/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Position,Date,Detail,picture")] Scenic scenic)
        {
            if (id != scenic.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(scenic);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScenicExists(scenic.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(scenic);
        }

        // GET: Scenics/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scenic = await _context.Scenics
                .FirstOrDefaultAsync(m => m.Id == id);
            if (scenic == null)
            {
                return NotFound();
            }

            return View(scenic);
        }

        // POST: Scenics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var scenic = await _context.Scenics.FindAsync(id);
            _context.Scenics.Remove(scenic);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ScenicExists(Guid id)
        {
            return _context.Scenics.Any(e => e.Id == id);
        }
    }
}

JiuFu/JiuFu.Web/Views/Home/Index.cshtml
@{
    Layout = "";
}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="~/css/bootstarpcss/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstarpcss/indexCSS.css" />
    <title>主页</title>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-xs-12" style="margin-top: 10%;">
                <div class="col-xs-1"></div>
                <div class="col-xs-4">
                    <a asp-action="Index" asp-controller="Entertainments">
                        <div class="thumbnail" style="text-align: center">
                            <img src="/Images/yvle.png" alt="...">
                            <h4>娱乐</h4>
                        </div>
                     </a>
                </div>
                <div class="col-xs-2"></div>
                <div class="col-xs-4">
                    <a asp-action="Index" asp-controller="Foods">
                        <div class="thumbnail" style="text-align: center">
                            <img src="~/Images/dianc.png" alt="...">
                            <h4>点餐</h4>
                        </div>
                        </a>
                </div>
                <div class="col-xs-1"></div>
            </div>
            <div class="col-xs-12" style="margin-top: 10px;">
                <div class="col-xs-1"></div>
                <div class="col-xs-4">
                    <a asp-action="Index" asp-controller="Laundry">
                        <div class="thumbnail" style="text-align: center">
                            <img src="~/Images/baojie.png" alt="...">
                            <h4>保洁</h4>
                        </div>
                    </a>
                </div>
                <div class="col-xs-2"></div>
                <div class="col-xs-4">
                    <a asp-action="Index" asp-controller="">
                        <div class="thumbnail" style="text-align: center">
                            <img src="~/Images/xutui.png" alt="...">
                            <h4>续退</h4>
                        </div>
                    </a>
                </div>
                <div class="col-xs-1"></div>
            </div>
            <div class="col-xs-12" style="margin-top: 10px;">
                <div class="col-xs-1"></div>
                <div class="col-xs-4">
                    <a asp-action="Index" asp-controller="Commodities">
                        <div class="thumbnail" style="text-align: center">
                            <img src="~/Images/zhoubian.png" alt="...">
                            <h4>周边</h4>
                        </div>
                    </a>
                </div>
                <div class="col-xs-2"></div>
                <div class="col-xs-4">
                    <a asp-action="Index" asp-controller="Scenics">
                        <div class="thumbnail" style="text-align: center">
                            <img src="~/Images/fengjing.png" alt="...">
                            <h4>风景</h4>
                        </div>
                        </a>
                </div>
                <div class="col-xs-1"></div>
            </div>
            <div class="col-xs-12" style="margin-top: 10px;">
                <div class="col-xs-1"></div>
                <div class="col-xs-4">
                    <a asp-action="Index" asp-controller="Goods">
                        <div class="thumbnail" style="text-align: center">
                            <img src="~/Images/songwu.png" alt="...">
                            <h4>送物</h4>
                        </div>
                    </a>
                </div>
                <div class="col-xs-2"></div>
                <div class="col-xs-4">
                    <a asp-action="Index" asp-controller="GoodsGR">
                        <div class="thumbnail" style="text-align: center">
                            <img src="~/Images/fengjing.png" alt="...">
                            <h4>个人</h4>
                        </div>
                    </a>
                </div>
                <div class="col-xs-1"></div>
            </div>
        </div>
    </div>    
    <script src="~/css/bootstarpcss/jquery-1.12.4.js"></script>
    <script src="~/css/bootstarpcss/bootstrap.min.js"></script>
</body>

JiuFu/JiuFu.Web/Views/Home/Login.cshtml
@model JiuFu.ViewModels.LoginVM
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>登录</title>

    <link rel="stylesheet" href="~/css/bootstarpcss/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstarpcss/FoodStyle.css">
    <link rel="stylesheet" href="~/css/bootstarpcss/LoginCSS.css">
</head>
<body>
    <div class="container" style="height:100%">
        <div class="row" style="height:100%">
            <form asp-action="Login" id="loginForm">
                <div class="col-xs-12" id="Longin">
                    <div class="input-group" id="Longintext">
                        <input asp-for="UserName" type="text" class="form-control" placeholder="账号" style="  border-radius: 5px;">
                    </div><br>
                    <div class="input-group" id="Longintext">
                        <input asp-for="Password" type="password" class="form-control" placeholder="密码" style="  border-radius: 5px;">
                    </div><br>
                </div>
                <div class="col-xs-12">
                    <div class="radio" style="display: block;text-align: center;">
                        <label>
                            <input asp-for="UserRole" type="radio" name="UserRole" id="optionsRadios1" value="普通注册用户" checked>用户
                        </label>
                        <label>
                            <input asp-for="UserRole" type="radio" name="UserRole" id="optionsRadios1" value="option1">厨师
                        </label>
                        <label>
                            <input asp-for="UserRole" type="radio" name="UserRole" id="optionsRadios1" value="option1">服务员
                        </label>
                    </div>
                </div>
                <div class="col-xs-12" style="margin-top:20px;">
                    <div class="col-xs-3"></div>
                    <div class="col-xs-6" style="margin:0 auto;">
                        <div class="btn-group btn-group-justified">
                            <a  onclick="document:loginForm.submit()"  class="btn btn-primary">登录</a>
                        </div>
                    </div>
                    <div class="col-xs-3"></div>
                </div>
            </form>
            <div class="col-xs-12" style="text-align: center;margin-top:30px;">
                <a asp-action="Register" asp-controller="Home">注册</a>
            </div>
        </div>
    </div>
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="~/css/bootstarpcss/jquery-1.12.4.js"></script>
    <script src="~/css/bootstarpcss/bootstrap.min.js"></script>
</body>
</html>

JiuFu/JiuFu.Web/Views/Home/Register.cshtml
@model JiuFu.ViewModels.UserAdd
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>注册</title>

    <link rel="stylesheet" href="~/css/bootstarpcss/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstarpcss/FoodStyle.css">
    <link rel="stylesheet" href="~/css/bootstarpcss/LoginCSS.css">
</head>
<body>
    <div class="container" style="height:100%">
        <div class="row" style="height:100%">
            <form asp-action="Register" id="loginForm">
                <div class="col-xs-12" id="Longin">
                    <div class="input-group" id="Longintext">
                        <div class="input-group" id="Longintext">
                            <input asp-for="Email" type="text" class="form-control" placeholder="邮箱" style="  border-radius: 5px;">
                        </div><br>
                        <div class="input-group" id="Longintext">
                            <input asp-for="MobileNumber" type="text" class="form-control" placeholder="手机号" style="  border-radius: 5px;">
                        </div><br>
                        <input asp-for="UserName" type="text" class="form-control" placeholder="账号" style="  border-radius: 5px;">
                    </div><br>
                    <div class="input-group" id="Longintext">
                        <input asp-for="Password" type="password" class="form-control" placeholder="密码" style="  border-radius: 5px;">
                    </div><br>
                    <div class="input-group" id="Longintext">
                        <input asp-for="PasswordComfirm" type="password" class="form-control" placeholder="确认密码" style="  border-radius: 5px;">
                    </div><br>
                </div>
                <div class="col-xs-12" style="margin-top:20px;">
                    <div class="col-xs-3"></div>
                    <div class="col-xs-6" style="margin:0 auto;">
                        <div class="btn-group btn-group-justified">
                            <a onclick="document:loginForm.submit()" class="btn btn-primary">注册</a>
                        </div>
                    </div>
                    <div class="col-xs-3"></div>
                </div>
            </form>
        </div>
    </div>
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="~/css/bootstarpcss/jquery-1.12.4.js"></script>
    <script src="~/css/bootstarpcss/bootstrap.min.js"></script>
</body>
</html>