JiuFu/JiuFu.Web/Controllers/NearController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JiuFu.ORM.SqlServer;
using Microsoft.AspNetCore.Mvc;

namespace JiuFu.Web.Controllers
{
    public class NearController : Controller
    {

       

        
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Delete()
        {
            return View();
        }
        public IActionResult Details()
        {
            return View();
        }
        public IActionResult Edit()
        {
            return View();
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

JiuFu/JiuFu.Web/Views/Near/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

JiuFu/JiuFu.Web/Views/Near/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

JiuFu/JiuFu.Web/Views/Near/Details.cshtml
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>水果</title>
    <link href="/css/bootstarpcss/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/bootstarpcss/zb.css">
</head>
<body>
    <div class="container" style="height:100%">
        <div class="row" id="div-header">
            <div class="col-xs-3">
                <a class="btn btn-default" asp-action="Index" role="button">返回</a>
              
            </div>
            <div class="col-xs-6">
                <p style="text-align:center;font-size:20px;">周边</p>
            </div>

        </div>
        <div class="row">
            <div id="awsl" class="col-xs-12">
                <a href="#" class="thumbnail">
                    <img src="图片/14.png" alt="...">
                </a>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <h4 style="padding-left:40px">这里是一个提示</h4>
                </div>
                <div class="col-xs-10">

                    <h4 style="padding-left:40px">数量:<input type="text" name="firstname"><br> </h4>
                </div>
                <div class="col-xs-10">
                    <h4 style="padding-left:40px">备注:</h4>
                </div>
                <div class="col-xs-11" style="padding-left:50px">
                    <textarea class="form-control" rows="3"
                              name=textarea></textarea>
                </div>
                <div class="col-xs-11" style="margin-top: 10px;">
                    <h4 id="awsl1" style="padding-left:40px;float: left;">￥50</h4> <a id="awsl2" style="float: right;" class="btn btn-default" href="#" role="button">结    算</a>
                </div>
            </div>
        </div>
    </div>
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="jquery-1.12.4.js"></script>
    <script src="bootstrap.min.js"></script>
</body>

JiuFu/JiuFu.Web/Views/Near/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

JiuFu/JiuFu.Web/Views/Near/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>周边</title>
    <link href="~/css/bootstarpcss/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/bootstarpcss/zb.css">
</head>
<body>
    <div class="container" style="height:100%">
        <div class="row" id="div-header">
            <div class="col-xs-3">
                <a class="btn btn-default" asp-controller="Near" asp-action="Index">返回</a>
              
            </div>
            <div class="col-xs-6">
                <p style="text-align:center;font-size:20px;">周边</p>
            </div>

        </div>
        <div class="row">
            <div class="row" id="main-rigth">
                <a href="01.html">
                    <div class="col-xs-4">
                        <div class="thumbnail">
                            <img src="图片/003.png" alt="...">
                        </div>
                    </div>
                    <div class="col-xs-1">
                        <h4 id="main-rigth1">鸡肉</h4>
                    </div>
                </a>
                <a href="02.html">
                    <div class="col-xs-4">
                        <div class="thumbnail">
                            <img src="图片/004.png" alt="...">
                        </div>
                    </div>
                    <div class="col-xs-1">
                        <h4 id="main-rigth1">咖啡</h4>
                    </div>
                </a>
            </div>
            <div class="row" id="main-rigth">
                <a href="03.html">
                    <div class="col-xs-4">
                        <div class="thumbnail">
                            <img src="图片/005.png" alt="...">
                        </div>
                    </div>
                    <div class="col-xs-1">
                        <h4 id="main-rigth1">陶罐</h4>
                    </div>
                </a>
                <a href="04.html">
                    <div class="col-xs-4">
                        <div class="thumbnail">
                            <img src="图片/007.png" alt="...">
                        </div>
                    </div>
                    <div class="col-xs-1">
                        <h4 id="main-rigth1">席子</h4>
                    </div>
                </a>
            </div>
            <div class="row" id="main-rigth">
                <a href="05.html">
                    <div class="col-xs-4">
                        <div class="thumbnail">
                            <img src="图片/006.png" alt="...">
                        </div>
                    </div>
                    <div class="col-xs-1">
                        <h4 id="main-rigth1">席子</h4>
                    </div>
                </a>
                <a href="06.html">
                    <div class="col-xs-4">
                        <div class="thumbnail">
                            <img src="图片/008.png" alt="...">
                        </div>
                    </div>
                    <div class="col-xs-1">
                        <h4 id="main-rigth1">旌旗</h4>
                    </div>
                </a>
            </div>

        </div>
    </div>
</body>
</html>